name: Scala Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Eclipse Temurin - JDK 21
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Tests
      run: sbt test
